services:
    dakala2:
        container_name: dk2
        image: yulinfeng/dakala2:1.0
        init: true
        environment: 
            APP_SECRET_KEY: 2d3fffefc3584a53f29cefcba175d2b92760d5fbd8929063d52a9615b74724fb
            APP_ADMIN_KEY: TOMCAT@YLF
            TZ: "Asia/Shanghai"
        volumes: 
            - ./data:/dakala/data
        ports:
            - 8888:8000