version: "2.2"
services:
  dakala:
    image: yulinfeng/dakala:1.0
    init: true
    container_name: dakala
    restart: always
    ports:
      - 8888:5000
    volumes:
      - /usr/local/docker/dakala/data:/usr/local/dakala/static/
