version: "2.2"
services:
  dakala:
    image: yulinfeng/dakala:1.0
    init: true
    container_name: dakala
    restart: always
    ports:
      - 8888:5000
    volumes:
      - /usr/local/docker/dakala/static:/usr/local/dakala/static/
      - /usr/local/docker/dakala/data:/usr/local/dakala/data/
    environment:
      SUPER_CODE: 536c0b339345616c1b33caf454454d8b8a190d6cX # 管理员手动全局打卡密钥
